import { ItemDef, InvItem } from "./types";

export const ITEM_REGISTRY: Record<string, ItemDef> = {
  fists: {
    id: "fists",
    name: "Кулак",
    type: "melee",
    damage: 8,
    range: 1.1,
    attackSpeed: 4.2,
    description: "Голые кулаки. Быстро, но наносит мало урона.",
    icon: "🥊",
  },
  knife: {
    id: "knife",
    name: "Боевой нож",
    type: "melee",
    damage: 18,
    range: 1.2,
    attackSpeed: 2.5,
    description: "Острое стальное лезвие. Тихий и смертоносный.",
    icon: "🔪",
  },
  bat: {
    id: "bat",
    name: "Бейсбольная бита",
    type: "melee",
    damage: 24,
    range: 1.5,
    attackSpeed: 1.4,
    description: "Тяжелая деревянная бита с отличной отдачей.",
    icon: "🏏",
  },
  sledgehammer: {
    id: "sledgehammer",
    name: "Кувалда",
    type: "melee",
    damage: 42,
    range: 1.7,
    attackSpeed: 0.9,
    description:
      "Обладает огромной сокрушительной силой, способной с легкостью разбивать двери и ящики.",
    icon: "🔨",
  },
  pistol: {
    id: "pistol",
    name: "Пистолет",
    type: "gun",
    damage: 16,
    range: 12,
    attackSpeed: 2.0,
    ammo: 15,
    maxAmmo: 15,
    bulletSpeed: 18,
    spread: 0.05,
    bulletCount: 1,
    soundName: "gunshot",
    description: "Стандартный служебный пистолет калибра 9 мм.",
    icon: "🔫",
  },
  shotgun: {
    id: "shotgun",
    name: "Дробовик",
    type: "gun",
    damage: 12, // per pellet (x5)
    range: 8,
    attackSpeed: 0.9,
    ammo: 8,
    maxAmmo: 8,
    bulletSpeed: 14,
    spread: 0.25,
    bulletCount: 5,
    soundName: "shotgun",
    description: "Разрушительное дробовик ближнего боя.",
    icon: "💥",
  },
  machinegun: {
    id: "machinegun",
    name: "Пулемет",
    type: "gun",
    damage: 14,
    range: 14,
    attackSpeed: 6.0,
    ammo: 30,
    maxAmmo: 30,
    bulletSpeed: 20,
    spread: 0.12,
    bulletCount: 1,
    soundName: "gunshot",
    description: "Скорострельный пистолет-пулемет.",
    icon: "⚡",
  },
  revolver: {
    id: "revolver",
    name: "Магнум револьвер",
    type: "gun",
    damage: 38,
    range: 15,
    attackSpeed: 1.1,
    ammo: 6,
    maxAmmo: 6,
    bulletSpeed: 22,
    spread: 0.02,
    bulletCount: 1,
    soundName: "shotgun",
    description: "Высококалиберная ручная пушка.",
    icon: "🤠",
  },
  medkit: {
    id: "medkit",
    name: "Аптечка",
    type: "consumable",
    healAmount: 40,
    description: "Мгновенно восстанавливает 40 единиц здоровья.",
    icon: "🩹",
  },
  beer: {
    id: "beer",
    name: "Пиво",
    type: "consumable",
    healAmount: 15,
    effectTrait: "Drunk",
    description:
      "Восстанавливает 15 единиц здоровья и дает смелость интоксикации.",
    icon: "🍺",
  },
  grenade: {
    id: "grenade",
    name: "Осколочная граната",
    type: "explosive",
    damage: 65,
    range: 8,
    description:
      "Взрывное метательное оружие, которое разбивает стены и толпы.",
    icon: "💣",
  },
  lockpick: {
    id: "lockpick",
    name: "Отмычка",
    type: "tool",
    description: "Бесшумно открывает запертые двери и сейфы.",
    icon: "🗝️",
  },
  zombie_claws: {
    id: "zombie_claws",
    name: "Инфицированные когти",
    type: "melee",
    damage: 14,
    range: 1.1,
    attackSpeed: 1.8,
    description:
      "Инфекционное поражение кожи в результате укуса и когтевого нападения.",
    icon: "🧟",
  },
};

let uidCounter = 1;

export function createInvItem(defId: string, count: number = 1): InvItem {
  const def = ITEM_REGISTRY[defId] || ITEM_REGISTRY["fists"];
  return {
    uid: `item_${uidCounter++}_${defId}`,
    defId,
    count,
    ammo: def.ammo,
  };
}
